### ISSUE TITLE
Practica5_Edwin Ortiz Cruz_4US

### ISSUE THREAD

**Issue by EdwinOrtiz1412** [SistemasTecTlaxiaco/diseno-de-control-para-cajas-de-texto-EdwinOrtiz1412#2]
[practica5_Edwin Ortiz Cruz_4US.pdf](https://github.com/SistemasTecTlaxiaco/diseno-de-control-para-cajas-de-texto-EdwinOrtiz1412/files/8338347/practica5_Edwin.Ortiz.Cruz_4US.pdf)

**Comment by Gregorio012** [comment]
Calificación 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
